# Generated by Django 5.2.4 on 2025-08-05 15:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_tag_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together={("name", "user")},
        ),
    ]
