# Generated by Django 5.2.4 on 2025-08-07 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_alter_tag_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="tag",
            name="user",
        ),
    ]
