# Generated by Django 5.2.4 on 2025-08-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "Super Admin"),
                    ("admin", "Admin"),
                    ("user", "User"),
                ],
                default="user",
                max_length=20,
            ),
        ),
    ]
